import { AdminStats, UserProfile } from "@/types";
import { mockTutors } from "./tutors";

export const mockAdminStats: AdminStats = {
  totalUsers: 1420,
  totalStudents: 1180,
  totalTutors: 240,
  activeTutors: 195,
  pendingTutorApplications: 14,
  totalBookings: 8430,
  completedLessons: 7920,
  grossRevenue: 342500.0,
  platformFees: 61650.0, // 18% avg platform fee
  tutorPayouts: 280850.0,
  activeDisputes: 2,
};

export const mockPendingTutors: UserProfile[] = [
  {
    id: "usr-pen-1",
    email: "lucas.moreau@example.com",
    role: "TUTOR",
    firstName: "Lucas",
    lastName: "Moreau",
    displayName: "Lucas Moreau",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400",
    phone: "+33 7 89 01 23 45",
    country: "France",
    timezone: "Europe/Paris",
    preferredLanguage: "French",
    status: "PENDING",
    createdAt: "2026-08-23T14:30:00Z",
    updatedAt: "2026-08-23T14:30:00Z",
  },
  {
    id: "usr-pen-2",
    email: "priya.sharma@example.com",
    role: "TUTOR",
    firstName: "Priya",
    lastName: "Sharma",
    displayName: "Priya Sharma",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400",
    phone: "+91 98765 43210",
    country: "India",
    timezone: "Asia/Kolkata",
    preferredLanguage: "English",
    status: "PENDING",
    createdAt: "2026-08-23T16:00:00Z",
    updatedAt: "2026-08-23T16:00:00Z",
  },
  {
    id: "usr-pen-3",
    email: "mateo.silva@example.com",
    role: "TUTOR",
    firstName: "Mateo",
    lastName: "Silva",
    displayName: "Mateo Silva",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400",
    phone: "+55 11 98765 4321",
    country: "Brazil",
    timezone: "America/Sao_Paulo",
    preferredLanguage: "Portuguese",
    status: "PENDING",
    createdAt: "2026-08-24T01:10:00Z",
    updatedAt: "2026-08-24T01:10:00Z",
  },
];

export const mockAuditLogs = [
  {
    id: "aud-1",
    adminName: "Super Admin",
    action: "TUTOR_APPROVED",
    targetType: "TUTOR_PROFILE",
    targetId: mockTutors[0].id,
    targetName: mockTutors[0].user.displayName,
    details: "Approved application following verification of Oxford Ph.D. credentials.",
    createdAt: "2026-08-23T18:40:00Z",
  },
  {
    id: "aud-2",
    adminName: "Super Admin",
    action: "PAYOUT_RELEASED",
    targetType: "TUTOR_PAYOUT",
    targetId: "payout-882",
    targetName: "Marcus Thorne ($1,240.00)",
    details: "Automated batch payout completed via Stripe Connect.",
    createdAt: "2026-08-22T09:15:00Z",
  },
  {
    id: "aud-3",
    adminName: "Super Admin",
    action: "SUBJECT_CREATED",
    targetType: "SUBJECT",
    targetId: "sub-16",
    targetName: "UI/UX Design",
    details: "Created new technology subject with category mapping.",
    createdAt: "2026-08-20T12:00:00Z",
  },
  {
    id: "aud-4",
    adminName: "Super Admin",
    action: "DISPUTE_RESOLVED",
    targetType: "BOOKING_DISPUTE",
    targetId: "bk-disp-44",
    targetName: "Student refund issued ($42.00)",
    details: "Tutor technical outage confirmed; full credit refunded to student wallet.",
    createdAt: "2026-08-19T15:30:00Z",
  },
];
