import { TutorEarnings } from "@/types";

export const mockTutorEarnings: TutorEarnings = {
  totalGrossEarned: 4850.0,
  platformCommissionTotal: 873.0, // 18% commission
  netPayoutTotal: 3977.0,
  availableBalance: 680.0,
  pendingBalance: 240.0,
  currency: "USD",
  recentTransactions: [
    {
      id: "tx-1",
      date: "2026-08-20T11:00:00Z",
      studentName: "Alex Rivera",
      subjectName: "IELTS & TOEFL Prep",
      lessonDuration: 50,
      amount: 50.0,
      platformFee: 9.0,
      netAmount: 41.0,
      status: "PAID",
    },
    {
      id: "tx-2",
      date: "2026-08-19T14:30:00Z",
      studentName: "Clara Zhao",
      subjectName: "Business English",
      lessonDuration: 50,
      amount: 50.0,
      platformFee: 9.0,
      netAmount: 41.0,
      status: "PAID",
    },
    {
      id: "tx-3",
      date: "2026-08-18T16:00:00Z",
      studentName: "David Kim",
      subjectName: "IELTS Exam Mock",
      lessonDuration: 50,
      amount: 50.0,
      platformFee: 9.0,
      netAmount: 41.0,
      status: "PAID",
    },
    {
      id: "tx-4",
      date: "2026-08-16T18:00:00Z",
      studentName: "Fatima Al-Hassan",
      subjectName: "Conversational English",
      lessonDuration: 50,
      amount: 50.0,
      platformFee: 9.0,
      netAmount: 41.0,
      status: "PAID",
    },
    {
      id: "tx-5",
      date: "2026-08-15T10:00:00Z",
      studentName: "James O'Connor",
      subjectName: "Accent Reduction",
      lessonDuration: 50,
      amount: 50.0,
      platformFee: 9.0,
      netAmount: 41.0,
      status: "PAID",
    },
  ],
};
