import { Lesson } from "@/types";
import { mockBookings } from "./bookings";

export const mockLessons: Lesson[] = [
  {
    id: "les-1",
    bookingId: mockBookings[0].id,
    booking: mockBookings[0],
    studentId: mockBookings[0].studentId,
    student: mockBookings[0].student,
    tutorId: mockBookings[0].tutorId,
    tutor: mockBookings[0].tutor,
    subject: mockBookings[0].subject,
    scheduledStart: mockBookings[0].startTime,
    scheduledEnd: mockBookings[0].endTime,
    status: "SCHEDULED",
    videoRoomId: mockBookings[0].videoRoomId!,
    lessonNotes: "Focus area: IELTS Speaking Part 2 - Monologue structuring and discourse markers for 7.5+ band.",
    studentFeedback: "Review the topic cue cards attached in materials before our session.",
    privateTutorNotes: "Alex is strong on vocabulary but occasionally pauses when searching for idioms. Encourage fluid filler phrases.",
    materials: [
      {
        id: "mat-1",
        name: "IELTS_Speaking_Band_8_Descriptive_Vocabulary.pdf",
        sizeBytes: 1024 * 450,
        fileType: "application/pdf",
        url: "/mock-files/IELTS_Speaking_Band_8.pdf",
        uploadedByRole: "TUTOR",
        uploadedAt: "2026-08-22T10:00:00Z",
      },
      {
        id: "mat-2",
        name: "Mock_Speaking_Part2_Prompt_Cards.pdf",
        sizeBytes: 1024 * 280,
        fileType: "application/pdf",
        url: "/mock-files/Prompt_Cards.pdf",
        uploadedByRole: "TUTOR",
        uploadedAt: "2026-08-22T10:05:00Z",
      },
    ],
    hasStudentReviewed: false,
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-08-20T10:05:00Z",
  },
  {
    id: "les-2",
    bookingId: mockBookings[1].id,
    booking: mockBookings[1],
    studentId: mockBookings[1].studentId,
    student: mockBookings[1].student,
    tutorId: mockBookings[1].tutorId,
    tutor: mockBookings[1].tutor,
    subject: mockBookings[1].subject,
    scheduledStart: mockBookings[1].startTime,
    scheduledEnd: mockBookings[1].endTime,
    status: "SCHEDULED",
    videoRoomId: mockBookings[1].videoRoomId!,
    lessonNotes: "Multivariable Calculus: Partial Derivatives & Gradient Vectors intuition.",
    studentFeedback: "Please look over 3D coordinate plot examples.",
    privateTutorNotes: "Student has good single-variable intuition, transition to directional derivatives should be smooth.",
    materials: [
      {
        id: "mat-3",
        name: "Calculus_3_Vector_Fields_CheatSheet.pdf",
        sizeBytes: 1024 * 720,
        fileType: "application/pdf",
        url: "/mock-files/Vector_Fields.pdf",
        uploadedByRole: "TUTOR",
        uploadedAt: "2026-08-21T14:00:00Z",
      },
    ],
    hasStudentReviewed: false,
    createdAt: "2026-08-21T14:00:00Z",
    updatedAt: "2026-08-21T14:05:00Z",
  },
  {
    id: "les-3",
    bookingId: mockBookings[3].id,
    booking: mockBookings[3],
    studentId: mockBookings[3].studentId,
    student: mockBookings[3].student,
    tutorId: mockBookings[3].tutorId,
    tutor: mockBookings[3].tutor,
    subject: mockBookings[3].subject,
    scheduledStart: mockBookings[3].startTime,
    scheduledEnd: mockBookings[3].endTime,
    actualStart: "2026-08-18T18:01:00Z",
    actualEnd: "2026-08-18T18:52:00Z",
    status: "COMPLETED",
    videoRoomId: mockBookings[3].videoRoomId!,
    lessonNotes: "Building custom decorators in Python, memory management, and generator pipelines.",
    studentFeedback: "Superb session! Alex quickly picked up generator state and lazy evaluation. Practice writing a file streaming pipeline for next time.",
    privateTutorNotes: "Excellent grasp. Next lesson we move directly into async/await and asyncio event loops.",
    materials: [
      {
        id: "mat-4",
        name: "Python_Advanced_Decorators_Code_Sample.py",
        sizeBytes: 1024 * 12,
        fileType: "text/plain",
        url: "/mock-files/decorators.py",
        uploadedByRole: "TUTOR",
        uploadedAt: "2026-08-18T19:00:00Z",
      },
    ],
    hasStudentReviewed: true,
    createdAt: "2026-08-14T11:00:00Z",
    updatedAt: "2026-08-18T19:00:00Z",
  },
];
