import { UserProfile, LearningProgress } from "@/types";

export const mockCurrentUser: UserProfile = {
  id: "usr-student-current",
  email: "alex.rivera@example.com",
  role: "STUDENT",
  firstName: "Alex",
  lastName: "Rivera",
  displayName: "Alex Rivera",
  avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=400",
  phone: "+1 (555) 987-6543",
  country: "United States",
  timezone: "America/New_York",
  preferredLanguage: "English",
  status: "ACTIVE",
  createdAt: "2024-05-10T12:00:00Z",
  updatedAt: "2026-08-20T16:00:00Z",
};

export const mockStudents: UserProfile[] = [
  mockCurrentUser,
  {
    id: "usr-stu-2",
    email: "clara.zhao@example.com",
    role: "STUDENT",
    firstName: "Clara",
    lastName: "Zhao",
    displayName: "Clara Zhao",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400",
    country: "Singapore",
    timezone: "Asia/Singapore",
    preferredLanguage: "English",
    status: "ACTIVE",
    createdAt: "2024-06-01T10:00:00Z",
    updatedAt: "2026-08-22T08:00:00Z",
  },
  {
    id: "usr-stu-3",
    email: "david.kim@example.com",
    role: "STUDENT",
    firstName: "David",
    lastName: "Kim",
    displayName: "David Kim",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400",
    country: "South Korea",
    timezone: "Asia/Seoul",
    preferredLanguage: "English",
    status: "ACTIVE",
    createdAt: "2024-06-15T11:00:00Z",
    updatedAt: "2026-08-15T09:00:00Z",
  },
  {
    id: "usr-stu-4",
    email: "fatima.al-hassan@example.com",
    role: "STUDENT",
    firstName: "Fatima",
    lastName: "Al-Hassan",
    displayName: "Fatima Al-Hassan",
    avatarUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=400",
    country: "Qatar",
    timezone: "Asia/Qatar",
    preferredLanguage: "Arabic",
    status: "ACTIVE",
    createdAt: "2024-07-01T14:00:00Z",
    updatedAt: "2026-08-18T10:00:00Z",
  },
];

export const mockStudentProgress: LearningProgress = {
  totalHoursLearned: 48.5,
  completedLessons: 32,
  activeSubjects: 3,
  learningStreakDays: 14,
  goals: [
    {
      id: "goal-1",
      studentId: mockCurrentUser.id,
      title: "Score 7.5+ in IELTS Speaking & Writing",
      description: "Target band for master's university admission in the UK.",
      targetDate: "2026-11-15",
      progressPercent: 75,
      status: "IN_PROGRESS",
      subjectId: "sub-15",
      subjectName: "IELTS & TOEFL Prep",
      createdAt: "2026-06-01T00:00:00Z",
    },
    {
      id: "goal-2",
      studentId: mockCurrentUser.id,
      title: "Master Multivariable Calculus & Linear Algebra",
      description: "Prepare for undergraduate engineering coursework.",
      targetDate: "2026-12-20",
      progressPercent: 60,
      status: "IN_PROGRESS",
      subjectId: "sub-2",
      subjectName: "Mathematics",
      createdAt: "2026-06-15T00:00:00Z",
    },
    {
      id: "goal-3",
      studentId: mockCurrentUser.id,
      title: "Conversational Spanish Fluency (B1/B2)",
      description: "Confident speaking for work travel in Latin America.",
      targetDate: "2027-01-30",
      progressPercent: 40,
      status: "IN_PROGRESS",
      subjectId: "sub-3",
      subjectName: "Spanish",
      createdAt: "2026-07-01T00:00:00Z",
    },
  ],
};
