import { Subject } from "@/types";

export const mockSubjects: Subject[] = [
  {
    id: "sub-1",
    name: "English",
    slug: "english",
    category: "Languages",
    description: "Master conversational fluency, grammar, IELTS/TOEFL exam prep, and business English with certified native tutors.",
    iconName: "Languages",
    tutorCount: 142,
    popular: true,
  },
  {
    id: "sub-2",
    name: "Mathematics",
    slug: "mathematics",
    category: "Mathematics",
    description: "From elementary arithmetic to calculus, linear algebra, statistics, and SAT/ACT math problem solving.",
    iconName: "Calculator",
    tutorCount: 88,
    popular: true,
  },
  {
    id: "sub-3",
    name: "Spanish",
    slug: "spanish",
    category: "Languages",
    description: "Learn Spanish for travel, DELE certification, high school AP prep, or native Latin American and Castilian fluency.",
    iconName: "Globe",
    tutorCount: 65,
    popular: true,
  },
  {
    id: "sub-4",
    name: "Python & Data Science",
    slug: "python-data-science",
    category: "Technology",
    description: "Learn Python from scratch, data analysis with Pandas, machine learning, and algorithmic coding interviews.",
    iconName: "Code",
    tutorCount: 52,
    popular: true,
  },
  {
    id: "sub-5",
    name: "Physics",
    slug: "physics",
    category: "Sciences",
    description: "Understand mechanics, electromagnetism, thermodynamics, AP Physics, and university physics foundations.",
    iconName: "Atom",
    tutorCount: 39,
    popular: true,
  },
  {
    id: "sub-6",
    name: "French",
    slug: "french",
    category: "Languages",
    description: "Delve into French pronunciation, DELF/DALF certifications, literature, and everyday Parisian conversation.",
    iconName: "BookOpen",
    tutorCount: 46,
    popular: true,
  },
  {
    id: "sub-7",
    name: "Chemistry",
    slug: "chemistry",
    category: "Sciences",
    description: "Organic chemistry, molecular structures, periodic table concepts, and AP Chemistry test preparation.",
    iconName: "FlaskConical",
    tutorCount: 31,
    popular: false,
  },
  {
    id: "sub-8",
    name: "Biology",
    slug: "biology",
    category: "Sciences",
    description: "Cellular biology, genetics, human anatomy, MCAT preparation, and environmental sciences.",
    iconName: "Dna",
    tutorCount: 28,
    popular: false,
  },
  {
    id: "sub-9",
    name: "German",
    slug: "german",
    category: "Languages",
    description: "Learn German for work, Goethe-Institut exam preparation, or university studies in Germany, Austria, and Switzerland.",
    iconName: "Languages",
    tutorCount: 34,
    popular: false,
  },
  {
    id: "sub-10",
    name: "Web Development (React & Node)",
    slug: "web-development",
    category: "Technology",
    description: "Build full-stack web applications with React, Next.js, Node.js, TypeScript, and modern database backends.",
    iconName: "Laptop",
    tutorCount: 48,
    popular: true,
  },
  {
    id: "sub-11",
    name: "Business & Management",
    slug: "business-management",
    category: "Business",
    description: "Strategic marketing, entrepreneurship, finance fundamentals, and case interview coaching.",
    iconName: "Briefcase",
    tutorCount: 22,
    popular: false,
  },
  {
    id: "sub-12",
    name: "Music Theory & Piano",
    slug: "piano-music-theory",
    category: "Arts & Music",
    description: "Classical and modern piano instruction, sight-reading, ear training, and ABRSM music theory prep.",
    iconName: "Music",
    tutorCount: 19,
    popular: false,
  },
  {
    id: "sub-13",
    name: "Arabic",
    slug: "arabic",
    category: "Languages",
    description: "Modern Standard Arabic (MSA), Egyptian and Levantine dialects, Quranic recitation and Arabic script.",
    iconName: "Globe",
    tutorCount: 26,
    popular: false,
  },
  {
    id: "sub-14",
    name: "Swahili",
    slug: "swahili",
    category: "Languages",
    description: "East African Swahili language, cultural nuances, conversational practice, and grammar.",
    iconName: "Languages",
    tutorCount: 18,
    popular: false,
  },
  {
    id: "sub-15",
    name: "IELTS & TOEFL Prep",
    slug: "ielts-toefl-prep",
    category: "Test Prep",
    description: "Targeted band score 7.5+ strategies, essay correction, speaking mocks, and timing techniques.",
    iconName: "GraduationCap",
    tutorCount: 77,
    popular: true,
  },
  {
    id: "sub-16",
    name: "UI/UX Design",
    slug: "ui-ux-design",
    category: "Technology",
    description: "Figma mastery, design systems, UX research methods, portfolio reviews, and product design fundamentals.",
    iconName: "Palette",
    tutorCount: 21,
    popular: false,
  },
];
