import { TutorProfile } from "@/types";
import { mockSubjects } from "./subjects";
import { mockLanguages } from "./languages";

export const mockTutors: TutorProfile[] = [
  {
    id: "tut-1",
    userId: "usr-tut-1",
    slug: "dr-elena-rostova",
    user: {
      id: "usr-tut-1",
      email: "elena.rostova@example.com",
      role: "TUTOR",
      firstName: "Elena",
      lastName: "Rostova",
      displayName: "Dr. Elena Rostova",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
      phone: "+1 (555) 234-5678",
      country: "United Kingdom",
      timezone: "Europe/London",
      preferredLanguage: "English",
      status: "ACTIVE",
      createdAt: "2024-01-15T08:00:00Z",
      updatedAt: "2026-08-01T12:00:00Z",
    },
    headline: "Oxford PhD in Pure Math • 10+ Yrs Experience with Calculus, SAT & Olympiad Math",
    bio: "Hello! I am a passionate mathematics educator holding a doctorate from the University of Oxford. Over the past decade, I've mentored 300+ students from high school to graduate levels. My teaching method focuses on deep conceptual understanding rather than rote memorization, demystifying abstract theorems with visual geometric intuition.",
    hourlyRate: 65,
    currency: "USD",
    yearsExperience: 10,
    teachingStyle: "Structured, Socratic & Intuitive Problem-Solving",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.98,
    reviewCount: 142,
    totalLessons: 1240,
    totalStudents: 185,
    isFeatured: true,
    isSuperTutor: true,
    responseTimeMinutes: 12,
    attendanceRate: 99.4,
    subjects: [
      {
        id: "ts-1-1",
        subjectId: "sub-2",
        subject: mockSubjects[1], // Mathematics
        levels: ["Beginner", "Intermediate", "Advanced", "Exam Prep"],
        isPrimary: true,
      },
      {
        id: "ts-1-2",
        subjectId: "sub-5",
        subject: mockSubjects[4], // Physics
        levels: ["Intermediate", "Advanced", "Exam Prep"],
      },
    ],
    languages: [
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Native",
      },
      {
        languageId: "lang-ru",
        language: mockLanguages[10],
        proficiency: "Native",
      },
      {
        languageId: "lang-fr",
        language: mockLanguages[2],
        proficiency: "Intermediate",
      },
    ],
    repeatStudentRate: 94,
    education: [
      {
        id: "edu-1-1",
        degree: "Ph.D. in Pure Mathematics",
        institution: "University of Oxford",
        fieldOfStudy: "Algebraic Geometry & Topology",
        startYear: 2013,
        endYear: 2017,
        honors: "Doctoral Thesis Distinction • Clarendon Scholar",
        location: "Oxford, United Kingdom",
        isVerified: true,
      },
      {
        id: "edu-1-2",
        degree: "B.Sc. (Hons) in Mathematics & Physics",
        institution: "Imperial College London",
        fieldOfStudy: "Mathematical Sciences",
        startYear: 2010,
        endYear: 2013,
        honors: "First Class Honours (Dean's List)",
        location: "London, United Kingdom",
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-1-1",
        title: "Qualified Teacher Status (QTS) — Secondary Mathematics",
        issuer: "UK Department for Education (DfE)",
        issueYear: 2018,
        credentialId: "QTS-GB-884920",
        isVerified: true,
      },
      {
        id: "cert-1-2",
        title: "AP Calculus AB & BC Master Instructor Certification",
        issuer: "The College Board (USA)",
        issueYear: 2020,
        credentialId: "CB-AP-992143",
        isVerified: true,
      },
      {
        id: "cert-1-3",
        title: "International Baccalaureate (IB) DP Math Higher Level Examiner",
        issuer: "International Baccalaureate Organization",
        issueYear: 2021,
        credentialId: "IB-EX-44109",
        isVerified: true,
      },
    ],
    experience: [
      {
        id: "exp-1-1",
        role: "Senior Academic Mathematics Coach & Lead Educator",
        organization: "Sabina Edge Elite Faculty",
        location: "Remote / London, UK",
        startYear: 2021,
        endYear: "Present",
        description: "Mentoring high-achieving high school and university students in AP Calculus AB/BC, IB Math AA HL, Differential Equations, and Oxford/Cambridge STEP admission exams. Over 92% of students achieved 5s or 7s.",
        highlights: [
          "Developed custom visual intuition calculus curriculum with 3D interactive graphs",
          "Mentored 300+ students across US, UK, Singapore, and Switzerland",
          "Maintained a 4.98/5.0 rating over 1,240 completed 1-on-1 lessons",
        ],
      },
      {
        id: "exp-1-2",
        role: "Lecturer & Teaching Assistant in Pure Mathematics",
        organization: "University of Oxford, Mathematical Institute",
        location: "Oxford, UK",
        startYear: 2017,
        endYear: 2021,
        description: "Delivered undergraduate seminars and small-group tutorials in Linear Algebra, Multivariable Calculus, and Real Analysis for 1st and 2nd year mathematics undergraduates.",
        highlights: [
          "Awarded Oxford Faculty Commendation for Excellence in Undergraduate Teaching",
          "Authored comprehensive problem set solutions and revision study packs",
        ],
      },
      {
        id: "exp-1-3",
        role: "Head Mathematics Olympiad Coach",
        organization: "Westminster Academic Centre",
        location: "London, UK",
        startYear: 2014,
        endYear: 2017,
        description: "Trained gifted students for the British Mathematical Olympiad (BMO) and UKMT Senior Mathematical Challenge.",
        highlights: [
          "Coached 14 national gold medallists and 4 IMO team shortlist qualifiers",
        ],
      },
    ],
    curriculumHighlights: [
      "AP Calculus AB / BC (Limits, Derivatives, Integrals, Series Convergence)",
      "IB Mathematics: Analysis & Approaches HL/SL (Internal Assessments coaching)",
      "University Level: Linear Algebra, Multivariable Calculus, Differential Equations",
      "Competitive Exams: SAT Math (800 Target), ACT Math, GRE Math Subject Test",
      "Oxbridge Entrance: STEP (Sixth Term Examination Paper) & MAT coaching",
    ],
    methodology: [
      {
        title: "Visual & Geometric Intuition First",
        description: "We never memorize formulas blindly. Every theorem is explored with interactive 2D/3D visualizations and real-world intuition before formal algebraic proofs.",
      },
      {
        title: "Socratic Problem-Solving & Active Inquiries",
        description: "I guide you to discover the next step through targeted questions, building genuine mathematical confidence and analytical resilience.",
      },
      {
        title: "Customized Homework & Video Solution Notes",
        description: "Receive personalized practice problem sets after every lesson with annotated LaTeX PDF notes and targeted difficulty progression.",
      },
      {
        title: "Real-Time Collaborative Whiteboard",
        description: "Work seamlessly on our shared ultra-low latency canvas with LaTeX equation rendering, graph plotting, and instant screenshot saving.",
      },
    ],
    faqs: [
      {
        question: "What is your approach with students who have math anxiety or feel stuck?",
        answer: "I break complex multi-step problems down into small, bite-sized intuitions. We start from familiar ground and incrementally build up understanding so mathematics becomes logical and satisfying rather than intimidating.",
      },
      {
        question: "Do you help with AP Calculus / IB Math exam preparation?",
        answer: "Yes! Over 80% of my students prepare for AP Calculus AB/BC or IB Math AA/AI HL. We work through official past papers, analyze scoring rubrics, master timing strategies, and conquer high-weight FRQ free-response questions.",
      },
      {
        question: "What materials or software do I need for our lessons?",
        answer: "Just a computer with a stable internet connection and a microphone. A digital drawing tablet or touchscreen stylus is helpful for working through derivations together on our interactive whiteboard, but not required.",
      },
      {
        question: "How does the 25-minute trial lesson work?",
        answer: "In the trial, we review your current syllabus, diagnose your specific learning gaps, solve a couple of challenging problems together, and create a tailored roadmap for your target exam or grade goals.",
      },
    ],
    availabilityRules: [
      { id: "ar-1-1", dayOfWeek: 1, startTime: "09:00", endTime: "18:00", isActive: true },
      { id: "ar-1-2", dayOfWeek: 2, startTime: "09:00", endTime: "18:00", isActive: true },
      { id: "ar-1-3", dayOfWeek: 3, startTime: "09:00", endTime: "18:00", isActive: true },
      { id: "ar-1-4", dayOfWeek: 4, startTime: "09:00", endTime: "18:00", isActive: true },
      { id: "ar-1-5", dayOfWeek: 5, startTime: "10:00", endTime: "16:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2026-08-01T12:00:00Z",
  },
  {
    id: "tut-2",
    userId: "usr-tut-2",
    slug: "marcus-thorne",
    user: {
      id: "usr-tut-2",
      email: "marcus.thorne@example.com",
      role: "TUTOR",
      firstName: "Marcus",
      lastName: "Thorne",
      displayName: "Marcus Thorne",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400",
      phone: "+1 (555) 345-6789",
      country: "United States",
      timezone: "America/New_York",
      preferredLanguage: "English",
      status: "ACTIVE",
      createdAt: "2024-02-10T10:00:00Z",
      updatedAt: "2026-08-10T14:00:00Z",
    },
    headline: "Senior Software Architect • Ex-Google • Python, Full-Stack & LeetCode Mentor",
    bio: "Hey there! I'm a senior software engineer with 8+ years building high-scale distributed systems. I specialize in taking self-taught coders and university students to FAANG-ready engineers. We'll build real-world microservices, write clean idiomatic Python and TypeScript, and break down complex algorithms into simple mental models.",
    hourlyRate: 85,
    currency: "USD",
    yearsExperience: 8,
    teachingStyle: "Project-Driven, Live Coding & Systems Architecture",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 5.0,
    reviewCount: 98,
    totalLessons: 890,
    totalStudents: 120,
    isFeatured: true,
    isSuperTutor: true,
    responseTimeMinutes: 8,
    attendanceRate: 100,
    subjects: [
      {
        id: "ts-2-1",
        subjectId: "sub-4",
        subject: mockSubjects[3], // Python
        levels: ["Beginner", "Intermediate", "Advanced"],
        isPrimary: true,
      },
      {
        id: "ts-2-2",
        subjectId: "sub-10",
        subject: mockSubjects[9], // Web Dev
        levels: ["Beginner", "Intermediate", "Advanced"],
      },
    ],
    languages: [
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Native",
      },
      {
        languageId: "lang-es",
        language: mockLanguages[1],
        proficiency: "Intermediate",
      },
    ],
    education: [
      {
        id: "edu-2-1",
        degree: "B.S. in Computer Science",
        institution: "Carnegie Mellon University",
        fieldOfStudy: "Software Engineering & Algorithms",
        startYear: 2012,
        endYear: 2016,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-2-1",
        title: "AWS Certified Solutions Architect – Professional",
        issuer: "Amazon Web Services",
        issueYear: 2021,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-2-1", dayOfWeek: 1, startTime: "14:00", endTime: "22:00", isActive: true },
      { id: "ar-2-2", dayOfWeek: 3, startTime: "14:00", endTime: "22:00", isActive: true },
      { id: "ar-2-3", dayOfWeek: 5, startTime: "14:00", endTime: "20:00", isActive: true },
      { id: "ar-2-4", dayOfWeek: 6, startTime: "10:00", endTime: "18:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2026-08-10T14:00:00Z",
  },
  {
    id: "tut-3",
    userId: "usr-tut-3",
    slug: "sophie-dubois",
    user: {
      id: "usr-tut-3",
      email: "sophie.dubois@example.com",
      role: "TUTOR",
      firstName: "Sophie",
      lastName: "Dubois",
      displayName: "Sophie Dubois",
      avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400",
      phone: "+33 6 12 34 56 78",
      country: "France",
      timezone: "Europe/Paris",
      preferredLanguage: "French",
      status: "ACTIVE",
      createdAt: "2024-03-01T09:00:00Z",
      updatedAt: "2026-08-12T16:00:00Z",
    },
    headline: "Native Parisian • Certified Alliance Française Teacher • DELF/DALF & Conversational",
    bio: "Bonjour ! I am a certified French instructor born and raised in Paris with 7 years of full-time tutoring experience. Whether you're starting from zero, polishing your pronunciation for a trip to Provence, or preparing for DALF C1 certification, our lessons will be engaging, culturally immersive, and tailored to your rhythm.",
    hourlyRate: 42,
    currency: "USD",
    yearsExperience: 7,
    teachingStyle: "Immersive, Communicative & High-Energy",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.96,
    reviewCount: 115,
    totalLessons: 970,
    totalStudents: 140,
    isFeatured: true,
    isSuperTutor: true,
    responseTimeMinutes: 15,
    attendanceRate: 99.8,
    subjects: [
      {
        id: "ts-3-1",
        subjectId: "sub-6",
        subject: mockSubjects[5], // French
        levels: ["Beginner", "Intermediate", "Advanced", "Conversational", "Exam Prep"],
        isPrimary: true,
      },
    ],
    languages: [
      {
        languageId: "lang-fr",
        language: mockLanguages[2],
        proficiency: "Native",
      },
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Fluent",
      },
      {
        languageId: "lang-es",
        language: mockLanguages[1],
        proficiency: "Intermediate",
      },
    ],
    education: [
      {
        id: "edu-3-1",
        degree: "Master in FLE (Français Langue Étrangère)",
        institution: "Sorbonne Université",
        fieldOfStudy: "Applied Linguistics",
        startYear: 2014,
        endYear: 2016,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-3-1",
        title: "DAEFLE Certification",
        issuer: "Alliance Française Paris",
        issueYear: 2017,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-3-1", dayOfWeek: 1, startTime: "08:00", endTime: "17:00", isActive: true },
      { id: "ar-3-2", dayOfWeek: 2, startTime: "08:00", endTime: "17:00", isActive: true },
      { id: "ar-3-3", dayOfWeek: 3, startTime: "08:00", endTime: "17:00", isActive: true },
      { id: "ar-3-4", dayOfWeek: 4, startTime: "08:00", endTime: "17:00", isActive: true },
      { id: "ar-3-5", dayOfWeek: 5, startTime: "08:00", endTime: "15:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-03-01T09:00:00Z",
    updatedAt: "2026-08-12T16:00:00Z",
  },
  {
    id: "tut-4",
    userId: "usr-tut-4",
    slug: "gabriel-morales",
    user: {
      id: "usr-tut-4",
      email: "gabriel.morales@example.com",
      role: "TUTOR",
      firstName: "Gabriel",
      lastName: "Morales",
      displayName: "Gabriel Morales",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
      phone: "+34 600 123 456",
      country: "Spain",
      timezone: "Europe/Madrid",
      preferredLanguage: "Spanish",
      status: "ACTIVE",
      createdAt: "2024-01-20T11:00:00Z",
      updatedAt: "2026-08-15T10:00:00Z",
    },
    headline: "Native Spanish Expert • Business Spanish, DELE Examiner & Pronunciation Coach",
    bio: "¡Hola amigos! I am Gabriel from Madrid. As a certified DELE exam examiner and business communications consultant, I design highly interactive lessons emphasizing spontaneous dialogue, natural phrasing, and practical business negotiations.",
    hourlyRate: 38,
    currency: "USD",
    yearsExperience: 6,
    teachingStyle: "Conversational, Practical & Confidence-Building",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.94,
    reviewCount: 89,
    totalLessons: 710,
    totalStudents: 105,
    isFeatured: false,
    isSuperTutor: true,
    responseTimeMinutes: 20,
    attendanceRate: 99.1,
    subjects: [
      {
        id: "ts-4-1",
        subjectId: "sub-3",
        subject: mockSubjects[2], // Spanish
        levels: ["Beginner", "Intermediate", "Advanced", "Conversational", "Exam Prep"],
        isPrimary: true,
      },
    ],
    languages: [
      {
        languageId: "lang-es",
        language: mockLanguages[1],
        proficiency: "Native",
      },
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Fluent",
      },
    ],
    education: [
      {
        id: "edu-4-1",
        degree: "Licenciatura en Filología Hispánica",
        institution: "Universidad Complutense de Madrid",
        fieldOfStudy: "Spanish Philology",
        startYear: 2012,
        endYear: 2016,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-4-1",
        title: "Official DELE Examiner Accredited (A1-C2)",
        issuer: "Instituto Cervantes",
        issueYear: 2018,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-4-1", dayOfWeek: 2, startTime: "09:00", endTime: "19:00", isActive: true },
      { id: "ar-4-2", dayOfWeek: 3, startTime: "09:00", endTime: "19:00", isActive: true },
      { id: "ar-4-3", dayOfWeek: 4, startTime: "09:00", endTime: "19:00", isActive: true },
      { id: "ar-4-4", dayOfWeek: 5, startTime: "09:00", endTime: "19:00", isActive: true },
      { id: "ar-4-5", dayOfWeek: 6, startTime: "10:00", endTime: "16:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-01-20T11:00:00Z",
    updatedAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "tut-5",
    userId: "usr-tut-5",
    slug: "sarah-jenkins",
    user: {
      id: "usr-tut-5",
      email: "sarah.jenkins@example.com",
      role: "TUTOR",
      firstName: "Sarah",
      lastName: "Jenkins",
      displayName: "Sarah Jenkins, CELTA",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
      phone: "+1 (555) 678-9012",
      country: "Canada",
      timezone: "America/Toronto",
      preferredLanguage: "English",
      status: "ACTIVE",
      createdAt: "2024-01-10T14:00:00Z",
      updatedAt: "2026-08-18T11:00:00Z",
    },
    headline: "Cambridge CELTA Certified • IELTS Band 8.5 Coach • Accent Reduction Specialist",
    bio: "Hi! I am Sarah, a Canadian ESL educator with 9 years of international teaching experience across North America and Asia. I have helped over 400 students achieve their target IELTS 7.5+ band score for university admissions and immigration.",
    hourlyRate: 50,
    currency: "USD",
    yearsExperience: 9,
    teachingStyle: "Targeted, Rigorous & Encouraging",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.99,
    reviewCount: 210,
    totalLessons: 1850,
    totalStudents: 260,
    isFeatured: true,
    isSuperTutor: true,
    responseTimeMinutes: 5,
    attendanceRate: 100,
    subjects: [
      {
        id: "ts-5-1",
        subjectId: "sub-1",
        subject: mockSubjects[0], // English
        levels: ["Beginner", "Intermediate", "Advanced", "Conversational", "Exam Prep"],
        isPrimary: true,
      },
      {
        id: "ts-5-2",
        subjectId: "sub-15",
        subject: mockSubjects[14], // IELTS/TOEFL
        levels: ["Intermediate", "Advanced", "Exam Prep"],
      },
    ],
    languages: [
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Native",
      },
      {
        languageId: "lang-fr",
        language: mockLanguages[2],
        proficiency: "Professional",
      },
    ],
    education: [
      {
        id: "edu-5-1",
        degree: "B.A. in English Literature & Education",
        institution: "University of Toronto",
        fieldOfStudy: "Applied Pedagogy",
        startYear: 2011,
        endYear: 2015,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-5-1",
        title: "Cambridge CELTA (Pass A)",
        issuer: "Cambridge Assessment English",
        issueYear: 2016,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-5-1", dayOfWeek: 1, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-5-2", dayOfWeek: 2, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-5-3", dayOfWeek: 3, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-5-4", dayOfWeek: 4, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-5-5", dayOfWeek: 5, startTime: "08:00", endTime: "14:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-01-10T14:00:00Z",
    updatedAt: "2026-08-18T11:00:00Z",
  },
  {
    id: "tut-6",
    userId: "usr-tut-6",
    slug: "tariq-al-mansoori",
    user: {
      id: "usr-tut-6",
      email: "tariq.mansoori@example.com",
      role: "TUTOR",
      firstName: "Tariq",
      lastName: "Al-Mansoori",
      displayName: "Tariq Al-Mansoori",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
      phone: "+971 50 123 4567",
      country: "United Arab Emirates",
      timezone: "Asia/Dubai",
      preferredLanguage: "Arabic",
      status: "ACTIVE",
      createdAt: "2024-04-05T09:00:00Z",
      updatedAt: "2026-08-05T13:00:00Z",
    },
    headline: "Native Arabic Scholar • Modern Standard Arabic (MSA), Dialects & Media Arabic",
    bio: "Marhaban! I hold a degree from Cairo's Al-Azhar University and have taught Modern Standard Arabic and Gulf/Egyptian dialects for 8 years. My lessons combine grammar precision with rich cultural context and real audio-visual media.",
    hourlyRate: 35,
    currency: "USD",
    yearsExperience: 8,
    teachingStyle: "Systematic, Patient & Immersive",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.92,
    reviewCount: 64,
    totalLessons: 520,
    totalStudents: 75,
    isFeatured: false,
    isSuperTutor: false,
    responseTimeMinutes: 25,
    attendanceRate: 98.8,
    subjects: [
      {
        id: "ts-6-1",
        subjectId: "sub-13",
        subject: mockSubjects[12], // Arabic
        levels: ["Beginner", "Intermediate", "Advanced", "Conversational"],
        isPrimary: true,
      },
    ],
    languages: [
      {
        languageId: "lang-ar",
        language: mockLanguages[5],
        proficiency: "Native",
      },
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Fluent",
      },
    ],
    education: [
      {
        id: "edu-6-1",
        degree: "B.A. in Arabic Literature & Linguistics",
        institution: "Al-Azhar University",
        fieldOfStudy: "Classical Arabic & Grammar",
        startYear: 2012,
        endYear: 2016,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-6-1",
        title: "Certified Arabic for Non-Native Speakers (TAFL)",
        issuer: "AUC Cairo",
        issueYear: 2017,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-6-1", dayOfWeek: 0, startTime: "10:00", endTime: "19:00", isActive: true },
      { id: "ar-6-2", dayOfWeek: 1, startTime: "10:00", endTime: "19:00", isActive: true },
      { id: "ar-6-3", dayOfWeek: 2, startTime: "10:00", endTime: "19:00", isActive: true },
      { id: "ar-6-4", dayOfWeek: 3, startTime: "10:00", endTime: "19:00", isActive: true },
      { id: "ar-6-5", dayOfWeek: 4, startTime: "10:00", endTime: "19:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-04-05T09:00:00Z",
    updatedAt: "2026-08-05T13:00:00Z",
  },
  {
    id: "tut-7",
    userId: "usr-tut-7",
    slug: "amina-khamis",
    user: {
      id: "usr-tut-7",
      email: "amina.khamis@example.com",
      role: "TUTOR",
      firstName: "Amina",
      lastName: "Khamis",
      displayName: "Amina Khamis",
      avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=400",
      phone: "+254 700 123 456",
      country: "Kenya",
      timezone: "Africa/Nairobi",
      preferredLanguage: "Swahili",
      status: "ACTIVE",
      createdAt: "2024-02-28T07:00:00Z",
      updatedAt: "2026-08-20T08:00:00Z",
    },
    headline: "Native Swahili & Biology Instructor • University Lecturer & Cultural Guide",
    bio: "Jambo! I am Amina from Nairobi. With over 6 years of university tutoring in East African languages and high-school biology, I bring warmth, patience, and structured materials to every lesson.",
    hourlyRate: 30,
    currency: "USD",
    yearsExperience: 6,
    teachingStyle: "Warm, Engaging & Storytelling-Driven",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.97,
    reviewCount: 78,
    totalLessons: 640,
    totalStudents: 92,
    isFeatured: true,
    isSuperTutor: false,
    responseTimeMinutes: 10,
    attendanceRate: 99.5,
    subjects: [
      {
        id: "ts-7-1",
        subjectId: "sub-14",
        subject: mockSubjects[13], // Swahili
        levels: ["Beginner", "Intermediate", "Advanced", "Conversational"],
        isPrimary: true,
      },
      {
        id: "ts-7-2",
        subjectId: "sub-8",
        subject: mockSubjects[7], // Biology
        levels: ["Beginner", "Intermediate"],
      },
    ],
    languages: [
      {
        languageId: "lang-sw",
        language: mockLanguages[6],
        proficiency: "Native",
      },
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Fluent",
      },
    ],
    education: [
      {
        id: "edu-7-1",
        degree: "B.Ed. in Linguistics & Biological Sciences",
        institution: "University of Nairobi",
        fieldOfStudy: "Education & Pedagogy",
        startYear: 2014,
        endYear: 2018,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-7-1",
        title: "National Educators Board Certificate",
        issuer: "TSC Kenya",
        issueYear: 2019,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-7-1", dayOfWeek: 1, startTime: "07:00", endTime: "18:00", isActive: true },
      { id: "ar-7-2", dayOfWeek: 2, startTime: "07:00", endTime: "18:00", isActive: true },
      { id: "ar-7-3", dayOfWeek: 3, startTime: "07:00", endTime: "18:00", isActive: true },
      { id: "ar-7-4", dayOfWeek: 4, startTime: "07:00", endTime: "18:00", isActive: true },
      { id: "ar-7-5", dayOfWeek: 5, startTime: "07:00", endTime: "16:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-02-28T07:00:00Z",
    updatedAt: "2026-08-20T08:00:00Z",
  },
  {
    id: "tut-8",
    userId: "usr-tut-8",
    slug: "alexander-vogel",
    user: {
      id: "usr-tut-8",
      email: "alexander.vogel@example.com",
      role: "TUTOR",
      firstName: "Alexander",
      lastName: "Vogel",
      displayName: "Alexander Vogel",
      avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400",
      phone: "+49 30 12345678",
      country: "Germany",
      timezone: "Europe/Berlin",
      preferredLanguage: "German",
      status: "ACTIVE",
      createdAt: "2024-03-15T12:00:00Z",
      updatedAt: "2026-08-14T09:00:00Z",
    },
    headline: "Native German Tutor • Goethe-Zertifikat A1-C1 Prep • Business & Technical German",
    bio: "Guten Tag! I am Alexander from Berlin. With 7 years of teaching experience, I help engineers, medical professionals, and students master the German language with precision and ease. We focus on natural flow, cases, and specialized workplace vocabulary.",
    hourlyRate: 48,
    currency: "USD",
    yearsExperience: 7,
    teachingStyle: "Structured, Methodical & Clear",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.95,
    reviewCount: 92,
    totalLessons: 780,
    totalStudents: 110,
    isFeatured: false,
    isSuperTutor: true,
    responseTimeMinutes: 18,
    attendanceRate: 99.6,
    subjects: [
      {
        id: "ts-8-1",
        subjectId: "sub-9",
        subject: mockSubjects[8], // German
        levels: ["Beginner", "Intermediate", "Advanced", "Conversational", "Exam Prep"],
        isPrimary: true,
      },
    ],
    languages: [
      {
        languageId: "lang-de",
        language: mockLanguages[3],
        proficiency: "Native",
      },
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Fluent",
      },
    ],
    education: [
      {
        id: "edu-8-1",
        degree: "M.A. in Germanistik & Interkulturelle Kommunikation",
        institution: "Humboldt-Universität zu Berlin",
        fieldOfStudy: "German Language & Culture",
        startYear: 2013,
        endYear: 2017,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-8-1",
        title: "Goethe-Institut Certified DaF Trainer",
        issuer: "Goethe-Institut Berlin",
        issueYear: 2018,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-8-1", dayOfWeek: 1, startTime: "09:00", endTime: "17:00", isActive: true },
      { id: "ar-8-2", dayOfWeek: 2, startTime: "09:00", endTime: "17:00", isActive: true },
      { id: "ar-8-3", dayOfWeek: 4, startTime: "09:00", endTime: "17:00", isActive: true },
      { id: "ar-8-4", dayOfWeek: 5, startTime: "09:00", endTime: "15:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-03-15T12:00:00Z",
    updatedAt: "2026-08-14T09:00:00Z",
  },
  {
    id: "tut-9",
    userId: "usr-tut-9",
    slug: "mei-ling-chen",
    user: {
      id: "usr-tut-9",
      email: "meiling.chen@example.com",
      role: "TUTOR",
      firstName: "Mei-Ling",
      lastName: "Chen",
      displayName: "Mei-Ling Chen",
      avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=400",
      phone: "+886 912 345 678",
      country: "Taiwan",
      timezone: "Asia/Taipei",
      preferredLanguage: "Mandarin Chinese",
      status: "ACTIVE",
      createdAt: "2024-02-01T06:00:00Z",
      updatedAt: "2026-08-19T14:00:00Z",
    },
    headline: "HSK & TOCFL Certified Mandarin Tutor • Pinyin, Characters & Business Chinese",
    bio: "Nǐ hǎo! I am Mei-Ling, a certified Mandarin instructor with 5 years of experience helping beginners to advanced learners speak fluent Chinese with accurate tones and confidence.",
    hourlyRate: 36,
    currency: "USD",
    yearsExperience: 5,
    teachingStyle: "Visual, Interactive & Tone-Focused",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.96,
    reviewCount: 84,
    totalLessons: 670,
    totalStudents: 98,
    isFeatured: false,
    isSuperTutor: true,
    responseTimeMinutes: 14,
    attendanceRate: 99.7,
    subjects: [
      {
        id: "ts-9-1",
        subjectId: "sub-1",
        subject: {
          id: "sub-zh",
          name: "Mandarin Chinese",
          slug: "mandarin-chinese",
          category: "Languages",
          description: "Learn Mandarin tones, characters, HSK test preparation, and business Chinese.",
          iconName: "Globe",
        },
        levels: ["Beginner", "Intermediate", "Advanced", "Conversational", "Exam Prep"],
        isPrimary: true,
      },
    ],
    languages: [
      {
        languageId: "lang-zh",
        language: mockLanguages[4],
        proficiency: "Native",
      },
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Fluent",
      },
    ],
    education: [
      {
        id: "edu-9-1",
        degree: "B.A. in Teaching Chinese as a Second Language",
        institution: "National Taiwan Normal University",
        fieldOfStudy: "Chinese Applied Linguistics",
        startYear: 2015,
        endYear: 2019,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-9-1",
        title: "Certificate of Proficiency in Teaching Chinese",
        issuer: "Ministry of Education",
        issueYear: 2019,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-9-1", dayOfWeek: 1, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-9-2", dayOfWeek: 2, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-9-3", dayOfWeek: 3, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-9-4", dayOfWeek: 4, startTime: "08:00", endTime: "16:00", isActive: true },
      { id: "ar-9-5", dayOfWeek: 6, startTime: "09:00", endTime: "15:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-02-01T06:00:00Z",
    updatedAt: "2026-08-19T14:00:00Z",
  },
  {
    id: "tut-10",
    userId: "usr-tut-10",
    slug: "dr-arjun-nair",
    user: {
      id: "usr-tut-10",
      email: "arjun.nair@example.com",
      role: "TUTOR",
      firstName: "Arjun",
      lastName: "Nair",
      displayName: "Dr. Arjun Nair",
      avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400",
      phone: "+1 (555) 456-7890",
      country: "United States",
      timezone: "America/Chicago",
      preferredLanguage: "English",
      status: "ACTIVE",
      createdAt: "2024-01-25T15:00:00Z",
      updatedAt: "2026-08-21T18:00:00Z",
    },
    headline: "MIT PhD in Physics • AP & MCAT Physics Specialist • Organic Chemistry & Calculus",
    bio: "Hello! I am Dr. Arjun Nair. I obtained my doctorate in applied physics from MIT. I break down daunting physics formulas and chemical equations into intuitive principles that click immediately.",
    hourlyRate: 75,
    currency: "USD",
    yearsExperience: 11,
    teachingStyle: "First-Principles, Conceptual & Diagnostic",
    introVideoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    videoThumbnail: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=600",
    verificationStatus: "APPROVED",
    averageRating: 4.99,
    reviewCount: 165,
    totalLessons: 1420,
    totalStudents: 195,
    isFeatured: true,
    isSuperTutor: true,
    responseTimeMinutes: 10,
    attendanceRate: 100,
    subjects: [
      {
        id: "ts-10-1",
        subjectId: "sub-5",
        subject: mockSubjects[4], // Physics
        levels: ["Intermediate", "Advanced", "Exam Prep"],
        isPrimary: true,
      },
      {
        id: "ts-10-2",
        subjectId: "sub-7",
        subject: mockSubjects[6], // Chemistry
        levels: ["Intermediate", "Advanced", "Exam Prep"],
      },
      {
        id: "ts-10-3",
        subjectId: "sub-2",
        subject: mockSubjects[1], // Math
        levels: ["Advanced", "Exam Prep"],
      },
    ],
    languages: [
      {
        languageId: "lang-en",
        language: mockLanguages[0],
        proficiency: "Native",
      },
      {
        languageId: "lang-hi",
        language: mockLanguages[12],
        proficiency: "Native",
      },
    ],
    education: [
      {
        id: "edu-10-1",
        degree: "Ph.D. in Applied Physics",
        institution: "Massachusetts Institute of Technology (MIT)",
        fieldOfStudy: "Quantum Condensed Matter",
        startYear: 2011,
        endYear: 2016,
        isVerified: true,
      },
    ],
    certifications: [
      {
        id: "cert-10-1",
        title: "National Science Foundation Fellow",
        issuer: "NSF",
        issueYear: 2014,
        isVerified: true,
      },
    ],
    availabilityRules: [
      { id: "ar-10-1", dayOfWeek: 1, startTime: "13:00", endTime: "21:00", isActive: true },
      { id: "ar-10-2", dayOfWeek: 2, startTime: "13:00", endTime: "21:00", isActive: true },
      { id: "ar-10-3", dayOfWeek: 3, startTime: "13:00", endTime: "21:00", isActive: true },
      { id: "ar-10-4", dayOfWeek: 4, startTime: "13:00", endTime: "21:00", isActive: true },
      { id: "ar-10-5", dayOfWeek: 6, startTime: "10:00", endTime: "17:00", isActive: true },
    ],
    exceptions: [],
    createdAt: "2024-01-25T15:00:00Z",
    updatedAt: "2026-08-21T18:00:00Z",
  },
];
